server:
  port: 8763
spring:
  application:
    name: eureka-server
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    region: region-west
    service-url:
      zone1: http://localhost:8763/eureka/
      zone2: http://localhost:8764/eureka/
    availability-zones:
      region-west: zone3,zone4
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false
    remote-region-urls-with-name:
      region-east: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    metadata-map.zone: zone3