server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    region: region-east
    service-url:
      zone1: http://localhost:8761/eureka/
      zone2: http://localhost:8762/eureka/
    availability-zones:
      region-west: zone1,zone2
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false
    remote-region-urls-with-name:
      region-west: http://localhost:8763/eureka/
  instance:
    hostname: localhost
    metadata-map.zone: zone1