server:
  port: 10001
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    region: region-east
    service-url:
      zone1: http://localhost:8761/eureka/
      zone2: http://localhost:8762/eureka/
    availability-zones:
      region-west: zone1,zone2
  instance:
    metadata-map:
      zone: zone1